server:
  error:
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:mysql://localhost:3306/fitdiary
    username: root
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: metaclass.cux@gmail.com
    password: fxhwizxqdopajhfl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

cloudinary:
  url: cloudinary://988346186838798:HkCMSqB99uwY8VaPv5a3y7h6Eiw@hdjxm4zyg
