server:
  error:
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    username: AKIAS7TER7NVMI5UBKZB
    password: BGQ5081F5jcvoamPWpChDK87vLFL9C6lR44dB4rzqSQb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
cloudinary:
  url: cloudinary://988346186838798:HkCMSqB99uwY8VaPv5a3y7h6Eiw@hdjxm4zyg