server:
  error:
    include-message: never

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 0ca10b58484f3a
    password: c4e490e41f544c
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true