server:
  error:
    include-message: never

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    username: AKIAS7TER7NVMI5UBKZB
    password: BGQ5081F5jcvoamPWpChDK87vLFL9C6lR44dB4rzqSQb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true